import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import Image from 'next/image'

export default function Carousel() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
    <div className="container">
        <div className="row">
            <div id="carouselExampleSlidesOnly" className="carousel slide" data-ride="carousel">
                <div className="carousel-inner">
                    <div className="carousel-item active">
                    <Image className="d-block w-100" src="/bg-01.PNG" alt="First slide" width="1100" height="600"></Image>
                    </div>
                </div>
            </div>
        </div>
    <div className="row">
        <div className="col-md-3">
            <div className="card">
                    <Image className="card-img-top" src="/bg-01.PNG" alt="Card image cap" width="200" height="200"></Image>
                <div className="card-body">
                    <p className="card-text">Some quick example text to build on the card</p>
                </div>
            </div>
        </div>
        <div className="col-md-3">
            <div className="card">
                    <Image className="card-img-top" src="/bg-01.PNG" alt="Card image cap" width="200" height="200"></Image>
                <div className="card-body">
                    <p className="card-text">Some quick example text to build on the card</p>
                </div>
            </div>
        </div>
        <div className="col-md-3">
            <div className="card">
                    <Image className="card-img-top" src="/bg-01.PNG" alt="Card image cap" width="200" height="200"></Image>
                <div className="card-body">
                    <p className="card-text">Some quick example text to build on the card</p>
                </div>
            </div>
        </div>
        <div className="col-md-3">
            <div className="card">
                    <Image className="card-img-top" src="/bg-01.PNG" alt="Card image cap" width="200" height="200"></Image>
                <div className="card-body">
                    <p className="card-text">Some quick example text to build on the card</p>
                </div>
            </div>
        </div>
    </div>
    </div>
    
    </>
  )
}