import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import Stories from './stories'
import Carousel from './carousel'
import Investigions from './investigations'
import Video from './video'
import Sports from './sports'
import ScienceTechnology from './scienceTechnology'
import Economie from './Economie'

export default function MainContent() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <Stories />
      <Carousel />
      <Investigions />
      <Video />
      <Sports />
      <ScienceTechnology />
      <Economie />
    </>
  )
}