import Head from 'next/head'

export default function MainContent() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <div>
        <h1>Content</h1>
      </div>
    </>
  )
}