import Head from 'next/head'
import Header from './header'
import MainContent from './main-content'
import Footer from './footer'
import 'bootstrap/dist/css/bootstrap.css'

export default function Layout() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container">
        <Header />
        <MainContent />
        <Footer />
      </div>
     
    </>
  )
}