import Head from 'next/head'
import Layout from '../../components/layout'

export default function LatestNews() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <div>
        <Layout />
        <h1>latest news</h1>
      </div>
    </>
  )
}