import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import Image from 'next/image'
import Link from 'next/link'

export default function StoriesImage() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head> */}
      <div className="row px-4">
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-01.PNG" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-02.jpg" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-03.jpeg" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-04.jpg" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-02.jpg" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-01.PNG" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-03.jpeg" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-04.jpg" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-01.PNG" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className="col-md-1">
          <div className="card">
                <Link href="#"><Image className="rounded-circle" src="/bg-03.jpeg" alt="Card image cap" width="80" height="80"></Image></Link>
          </div>
        </div>
        <div className='col-md-2'>
          <button className="rounded-circle">More</button>
        </div>
    </div>
    </>
  )
}