import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from './header'

export default function Components() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <div>
        <Header />
      </div>
    </>
  )
}
