import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'

export default function Trends() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <div>
        <h1>latest news</h1>
      </div>
    </>
  )
}