import Head from 'next/head'
import 'bootstrap/dist/css/bootstrap.css'
import StoriesImage from './storiesImage'

export default function Stories() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
    
      <StoriesImage/>
    </>
  )
}