import Head from 'next/head'
import Link from 'next/link'
import 'bootstrap/dist/css/bootstrap.css'


export default function Header() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <div className="container">
        <nav className="navbar navbar-expand-lg navbar-light bg-light">
        <Link className="navbar-brand" href="/">CLIENT</Link>
        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
        </button>
        <div className="collapse navbar-collapse" id="navbarNav">
            <ul className="navbar-nav">
            <div className="nav-item active">
                <Link className="nav-link" href="/latestNews">Latest News</Link>
            </div>
            <div className="nav-item">
                <Link className="nav-link" href="/news">News</Link>
            </div>
            <div className="nav-item">
                <Link className="nav-link" href="/culture">Culture</Link>
            </div>
            <div className="nav-item">
                <Link className="nav-link" href="/trends">Trends</Link>
            </div>
            <div className="nav-item">
                <Link className="nav-link" href="/sports">Sports</Link>
            </div>
            <div className="nav-item">
                <Link className="nav-link" href="/mix">Mix</Link>
            </div>
            <div className="nav-item">
                <Link className="nav-link" href="/Economie">Economie</Link>
            </div>
            <div className="nav-item">
                <Link className="nav-link" href="/Sciencetechnology">Science and Technology</Link>
            </div>
            </ul>
        </div>
        </nav>
      </div>
    </>
  )
}